spring:
  application:
    name: Database Converter
server:
  port: 8081
migration:
  data:
    path: ./migration/data/
  extract:
    threads: 12
    threadBatchSize: 4
    fetchSize: 500
  transform:
    maps:
      path: maps/
    ddl:
      path: ./ddl/
    dml:
      path: ./dml/